# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python PyTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    environment:
      name: testing

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Start Redis
      uses: caiomarruda/redisearch-action@v1.0.1
      with:
        redis version: 2.6.0
    - name: Test with PyTest
      id: pytestext
      env:
          LOGURU_LEVEL: ${{ secrets.LOGURU_LEVEL }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        echo "--- Starting app in background"
        python3 code/app.py &
        echo "--- Sleep(3)"
        sleep 3
        echo "--- Starting PyTest"
        pytest code/tests
